[package]
name = "simple-deadlock-mod-manager"
version = "0.6.3"
description = "A simple Mod Manager for Deadlock"
authors = ["gabri3445"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "deadlock_mod_manager_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.7.0", features = [] }
tauri-typegen = "0.5.3"

[dependencies]
tauri = { version = "2.12.0", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
steamlocate = "2.1.1"
valve_pak = "0.1.0"
tauri-plugin-dialog = "2.8.0"
regex = "1.13.1"
rand = "0.10.3"
unrar = "0.5.8"
zip = "8.6.0"
directories = "6.0.0"
reqwest = { version = "0.13.5", features = ["stream"] }
url = "2.5.8"
tauri-plugin-http = "=2.7.0"
futures-util = "0.3.34"
sevenz-rust2 = "0.23.0"
tauri-plugin-log = "2"
log = "0.4.34"

[target."cfg(any(target_os = \"linux\", target_os = \"dragonfly\", target_os = \"freebsd\", target_os = \"openbsd\", target_os = \"netbsd\"))".dependencies]
wgpu = { version = "27.0.1", default-features = false, features = ["vulkan"] }
